### PR TITLE
feature: add autocomp editor

### PR DESCRIPTION
**Pull request by ngduc**
usage (as discussed in https://github.com/olifolkerd/tabulator/issues/1513)

```
column config:
{title:"Name", field:"name", editor:"autocomp", editorParams:{
    values:{
        "steve":"Steve Boberson",
        "bob":"Bob Jimmerson",
        "jim":"Jim Stevenson",
    }
}}
```

@olifolkerd this is just a basic autocomplete input, type a partial text & press "Down" key to select the first matched text. One enhancement can be navigating the matched items using arrow keys.

image

### CODE REVIEW

**Comment by ngduc** [comment]
I got the list navigation (up/down) working (using tabindex & .focus()), will update this PR tonight.

**Comment by ngduc** [comment]
@olifolkerd I need hover & focus styles for list items. Do you have css class names for those?
could you also try the PR? Thanks.

**Comment by ngduc** [comment]
@olifolkerd 

autocomp

**Comment by ngduc** [comment]
@olifolkerd did you have a chance to check this? I hope it can go into the next 4.1 version. Thanks.

**Comment by olifolkerd** [comment]
hey @ngduc 

I will look at merging this in this weekend,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ngduc 

Thanks for taking the time to put together something for this.

Unfortunately upon reviewing the code im afraid it strays too far from Tabulators coding style and coding practices to include at this point.

- The list is styled in javascript making it hard for users to customise its appearance
- The list is contained in the cell and overrides the overflow (rather than being absolutely positioned on the body) which could cause layout issues in serveral layout configurations
- The list navigation directly traverses the DOM tree to find its position. Tabulator works using virtual DOM design principals, so manipulation is done on data that triggers action on arrays.

Im going to put together something quick as an upgrade to the select/autocomp editor today for the 4.1 release as i need to get it out tomorrow, and would welcome any input on it that you may have for further improvements. it will certainly need a multi select mode adding.

Im am sincerely sorry for wasting your time, not giving you feedback sooner and not giving you a chance to make updates yourself. I usually work tightly with collaborators over time and guide the pull requests to fit with Tabulator, but sadly things have been a bit hectic at work of late so i havn't had the time to work with collaborators as much as i would like to. I promise that should you be kind enough to submit pull requests in future i will give them the time they deserve.

On the good news front, i am going to do my usual new version promotional work over the next week and will be heavily pushing your react wrapper, so you should hopefully see a spike in users this next month.

Cheers

Oli :)

**Comment by ducwings** [comment]
Np Oli, I knew that it may not fit the grid architecture. Can't wait to try 4.1, will update the wrapper also. Thanks for your review.

**Pull request closed without merging**
