### PR TITLE
update generated responsive content if data has changed

### PR DESCRIPTION
**Pull request by lekoala**
otherwise the content is never updated correctly

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @lekoala 

Could you explain a bit more about why this PR is needed, Im afraid a comment of "otherwise the content is never updated correctly" doesn't really explain what the current functionality is, what the issue is, or how this fixes it?

Cheers

Oli :)

**Comment by lekoala** [comment]
it's explained in detail here
https://github.com/olifolkerd/tabulator/issues/3749

let me know if you need further info

**Comment by olifolkerd** [comment]
@lekoala  Can you make sure you include the issue link in future PR's if they are related.

Cheers

Oli :)

**Comment by lekoala** [comment]
@olifolkerd sure, i tend to rely on github always showing related PR/issue, but i will include the link directly next time.
do you need anything else for this issue?

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for providing the context on this one, i will include it in this weekends patch release.

Cheers

Oli :)

**Pull request merged**
