### PR TITLE
created a lockfile as npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by jjech**
This allows setting child dependencies to specific versions. It was necessary
as gulp-cssnano is deprecated and depends an old version of cssnano, which
breaks the tabulator build process. See #2581 for full details.

### CODE REVIEW

**Comment by jjech** [comment]
By converting package-lock.json to shrinkwrapped with gulp-cssnano's child dependency of cssnano locked to 4.0.0, I'm able to build tabulator without any workarounds. Feel free to reject this PR though if for some reason using shrinkwrapped dependencies is undesirable.

I wasn't sure if I should open the PR to the master branch or to 4.6.

**Comment by olifolkerd** [comment]
Hey @jjech 

Thanks for your submission,

There is already an approved PR awaiting merge that upgrades the gulp infrastructure to version 4. [#2551](https://github.com/olifolkerd/tabulator/pull/2551)

Please make sure your proposed changes do not conflict with that.

On a side note, please don't contaminate other PR's to try and promote your own, i will review each PR when i have time. I have deleted the unrelated comment from the other PR.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
I'm not exactly sure what you mean by it's failing the first time @jjech . Have you tried wiping out all node_modules and reinstalling? My gulp-cssnano folder under node_modules doesn't event have another node_modules folder. 

image

**Comment by jjech** [comment]
Hi @Jojoshua!

Thank you for the screenshot. I can see that your gulp-cssnano/package.json has been modified from the final version 2.1.3 of gulp-cssnano released in 2018. Check the "cssnano" dependency version, around line 41. In the released gulp-cssnano it is 3.0.0, which is causing the current build failure with gulp. I'm expecting that you modified this to 4.0.0 or higher at some point while you were trying to get past the build failure. Can you check it and confirm?

From what I can tell, that is actually the only thing causing build failure right now. Unfortunately, the modified gulp-cssnano/package.json is not (and should not) be included in any PR outside of the official gulp-cssnano repository. Since the official repository is read-only now and no longer maintained, we have to use a different solution to force the gulp-cssnano/cssnano dependency to 4.0.0 or higher... using npm shrinkwrap to override the gulp-cssnano/cssnano dependency is one option that seems to be working well (hence this PR).

Here's the reproduction procedure I'm using to ensure I'm building from fresh tabulator sources.

(start in the node app's directory, delete node_modules/tabulator-tables)
1. npm install https://github.com/olifolkerd/tabulator/tarball/master
1.5. (you can use https://github.com/Jojoshua/tabulator/tarball/gulp4 to test your branch)
2. cd to node_modules/tabulator-tables directory for the app
3. npm install
4. gulp
4.1. (gulp should fail with the 'dead' error detailed in #2581)
4.2. npm ls browserslist
4.3. (check version of cssnano, it will be at 3.x due to gulp-cssnano's package.json)
5. edit tabulator-tables/node_modules/gulp-cssnano/package.json
5.5. change cssnano dependency from 3.0.0 to 4.0.0 (line 41)
6. npm install
7. gulp
7.5. (gulp should build successfully now)

You could then try repeating the procedure substituting https://github.com/jjech/tabulator/tarball/shrinkwrapDependencies in step 1, then the build should succeed on step 4.

Looking forward to hearing back from you! Nice work with PR #2551

**Comment by Jojoshua** [comment]
@jjech 

It looks like it was modified but that was just the date that I did npm install. I just tried this from scratch again and I have the same 5 files inside the gulp-cssnano folder.

I am using Windows 10, Node v13.1.0, NPM v 6.13.1

1. Create windows directory called fresh-test
2. Open command prompt to that folder and run "git clone https://github.com/olifolkerd/tabulator.git"
3. CD into the newly created tabulator folder
4. run "npm i"

That's it. When finished, the gulp-cssnano folder is as shown in the screenshot. 

Now at this point when I run "gulp" I get ReferenceError: primordials is not defined but after moving to gulp4 this error goes away.

**Comment by jjech** [comment]
Ok, that's good info. I will do some more testing tomorrow, it's possible that the issue only occurs on Linux or something with my node / npm versions.

-------- Original Message --------

**Comment by jjech** [comment]
Thanks, @Jojoshua. After additional testing across platforms, node versions, building directly from a cloned repository vs as a node_module for my app, and building tabulator as a module for a different react app than the one I'm working on, it seems that issue #2581 has something specifically to do with my project and/or dev VM environment. I'm going to close this PR as well as the issue, as it seems clear the issue needs to be addressed in my project somehow (or I can use the workaround of editing gulp-cssnano/package.json in my environment).

gulp4 branch definitely resolves the primordials build failure you mentioned, and seems to be building well outside of my user context. If I find out more details later about why this fails within my context, I may reopen the issue and/or open a new PR if it seems applicable to other users. At present, there is not enough info on what is causing #2581.

**Pull request closed without merging**
