### PR TITLE
Check rowVal is valid in 'like' filter.

### PR DESCRIPTION
**Pull request by dpatel20**
Changes as per #1145.

I am submitting my first *ever* pull request (ever means on any project!! Go gently if I have done something wrong).

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @dpatel20 

Great to hear you have chosen Tabulator for your first pull requests!

I have a couple of bits of feedback for you on the changes, that will need updating before i can accept the request.

First of all you have used a "!=" in your code, could you please make sure it is a "!==" instead as it is more specific.

In the second comparison in that if just checks to see that rowVal is truthey, which will call it to fail if the value of the row is 0 or "" both of which are valid values.

what you could do instead is check that the value is not null ```rowVal !== null``` and then on the row below cast any other value to a string:
```js
String(rowVal).toLowerCase()
```
instead of
```js
rowVal.toLowerCase()
```

I hope that makes sense.

Let me know if you have any other questions.

Cheers

Oli :)

**Comment by dpatel20** [comment]
Hi Oli -

I see my secret amateur programmer status is now out! ;)

I took my changes based on what I had seen online assuming that `!=` had to be used rather than `!==`. I seem to remember coming across an issue where I used `!==` and it did not work as expected (and see this [comment](https://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in/28475133#comment38025689_5515385)). And [here](https://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in/28475133) I had seen about checking if truthy using `if(someVar)`.

And then the following links that I have seen after checking again suggest otherwise:
https://stackoverflow.com/questions/3390396/how-to-check-for-undefined-in-javascript
https://stackoverflow.com/questions/2647867/how-to-determine-if-variable-is-undefined-or-null

So I am totally confused as to the best way (in 2018) to test for `null` or `undefined`. I am willing to bow to your vastly superior knowledge on this...

**Comment by olifolkerd** [comment]
Hey @dpatel20 

Great stuff, that is looking much better! The final change i would ask for is that you use curly braces in your if/else statement to match the coding style of the rest of Tabulator.

Once that is in i will be happy to merge in the pull request.

Cheers

Oli :)

**Comment by dpatel20** [comment]
Take 3 - bet you wish you'd just done it yourself! :)

Thanks for the patience and tutorial.

**Comment by olifolkerd** [comment]
Approved!!!

Great work, thanks!

Pull requests are very rarely simple, you will always have a bit and back and forth with the people who maintain the library.

Keep up the good work, let me know if you have any other suggestions.

Cheers

Oli :)

**Pull request merged**
