### PR TITLE
adding class to row based on its depth

### PR DESCRIPTION
**Pull request by RaquelAM**
Enhancement based on issue #2362

### CODE REVIEW

**Comment by vini-brito** [comment]
Awesome! Came here just looking for this.

**Comment by olifolkerd** [comment]
Hey @RaquelAM 

Thanks for your PR, that is a very useful update.

Before i merge things in, could i ask you to make one tweak;

- you seem to be creating a ***element*** variable that is unneeded as you are only using it once. could you remove the variable definition and call call `row.element.classList` instead

Cheers

Oli :)

**Comment by RaquelAM** [comment]
@olifolkerd Hi!
The correction is already made :D
Thanks

**Comment by olifolkerd** [comment]
Hey @RaquelAM 

Thank you for the very fast update!

Consider this approved, i will merge it in with the next minor version update!

Thanks for your contribution

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This will be officially released in the 4.6 version in a few weeks time.

Cheers

Oli :)

**Pull request merged**
