### PR TITLE
GitHub actions and eslint config - warning only for now

### PR DESCRIPTION
**Pull request by rathboma**
@olifolkerd here's a much simpler start to your eslint journey:

1. Adds github actions workflows that do two things:
  - checks no one has changed files in `dist`, or committed a yarn.lock
  - runs eslint, and (right now) doesn't ever fail, just prints warnings
2. Adds good eslint config, but also adds a plugin to turn all errors into warnings for the timebeing

Some things you could do next:

If you want to, you can run `npx eslint --fix` and it will auto-fix a number of issues (like # tabs for indentation), but you will end up with a big PR of changes, but that's easier to manage anyway.

You could also enable eslint errors for all PRs and have it only look at changed files using a plugin like this:
https://github.com/tj-actions/eslint-changed-files

That way you could have contributors slowly fixing up your codebase as you go :-D

### CODE REVIEW

**Comment by rathboma** [comment]
I made a PR on my fork to show you how it would work: https://github.com/beekeeper-studio/tabulator/pull/2

See how it marks my PR as failed because my PR has dist changes. Just what we want!

**Comment by rathboma** [comment]
A nice benefit of doing it this way is you still get eslint warnings in VSCode, so you can fix problems over time if you don't want to do big PRs:

image

**Comment by olifolkerd** [comment]
Hey @rathboma 

That looks great, i will schedule this for inclusion in the next minor release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@rathboma 

Thanks for getting this all togeather, im gonna merge it into the 5.3 branch and will have a play with it all ready for the release in a few weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Ive tried `npx eslint --fix` but it dosn't seem to do anything, the command runs, dosn't do anything in the console then almost immediately finishes, no errors. ive tried disabling the only-warn plugin but that dosnt seem to help.

Any Thoughts?

Cheers

Oli :)

**Comment by rathboma** [comment]
Off the top of my head you need to specify the directory?

npx eslint src

For example

**Comment by olifolkerd** [comment]
Hey @rathboma 

All good, i was being a muppet, had the terminal in the wrong directory lol.

Thanks for the PR without the fixes, that was exactly what i needed, it has been really helpful to go through the issues one. Helped me understand about how eslint works and helped me to customize the rules a little more.

I have pushed this to the 5.3 branch (which will be released in a few weeks), along with all the rule tweaks and all the fixes that eslint highlighted was needed. Ive also remove the warnings only setting so things are classed as errors now i understand the ruleset.

Am i correct in assuming that once these have been merged into master, any future PR's will then automatically have the tests run because of the `lint-and-test` workflow you have added?

Cheers

Oli :)

**Comment by rathboma** [comment]
Correct! Yeah it'll help folks solve those problems on their own

**Pull request merged**
