### PR TITLE
Added Column controls to headers and more

### PR DESCRIPTION
**Pull request by AbsAlnaffakh**
Each column can now have a Sort, Freeze, Group, Hide controls available through a dropdown menu on the header, this overcomes the limitations of having to set such options before rendering the grid or do so after rendering but externally.

Modifications were made to how freezing works, now it will order columns then freeze, allowing multiple columns to freeze even if they are not next to each other.

You can add the below to the column definition to make use of new features:
headerControls: true, sortControl: true, groupControl: true, freezeControl: true, visibilityControl: true, headerFilter: true, headerSort: false

You can now also apply multiple header filters by typing in values seperated by semicolons.

There might be more features which I forgot about.

Do excuse any messiness I am still new to front end development, I am aware of where improvements can be made and will do so when I can.

Thanks for creating this awesome grid!

### CODE REVIEW

**Comment by AbsAlnaffakh** [comment]
The select menu is being used horribly to hold the controls on the header but it was one way of not having to change overflow properties, which causes issues when scrolling (don't know why!), I can replace it with a absolute element that is not part of the grid and can be displayed above it utilising a z-index. I have done this and seems to work nicely for a custom editor I created.

**Comment by olifolkerd** [comment]
Hey @AbsAlnaffakh 

Thanks for your contribution to Tabulator, it is always great to have input from the community :D

Just a couple of pointers before i chat about the Pull request, when you are looking to make significant changes to Tabulator, could you get in touch with me first to discuss your ideas so i can make sure they can fit in with the road-map and wont conflict with anything anyone else is working on.

Also could you please avoid suggesting version numbers in your pull requests, they should have a title  that reflects their contents, version numbers are defined by the [roadmap](https://trello.com/b/rPZ0Yavc/tabulator-roadmap) and will be incremented as needed, in this case your changes fit in nicely with next months 3.4 release which focuses on editors/sorters/filtering etc, so i will look at including it in that. I generally prefer to have any major pull requests submitted against a pre-agreed version branch, rather than on the master branch, which i try to keep clear for the official releases.

So now onto the good stuff, i really like your ideas, and think they will make a great addition to Tabulator, i will download your updates and have a play this evening and get back to you if any tweaks need to be made before i accept the pull request.

Could i ask that your resubmit this request on the 3.4 branch as that is where it will be deployed. i am looking to do an official release of the 3.4 branch in the next couple of weeks.

Keep up the good work!

Cheers

Oli

**Comment by AbsAlnaffakh** [comment]
One thing worth mentioning is that I downloaded your project off GitHub a while ago and all the changes were being made on my local copy, things may have gotten out of sink with what is on Git Hub, perhaps I should update and submit another pull request? This explains why it seems that I may have rolled back on some fixes . This must be causing you a headache now, sorry!

**Comment by olifolkerd** [comment]
Hey @AbsAlnaffakh 

Ive had a chance to look at your pull request and im afraid i wont be able to accept it in its current state, but i do have some pointers for you, i have added some comments in the code, and have a summary of my feedback below.

For starters you seem to be making a lot of changes for one commit. a Commit should represent one functional change to the system to make it easier to track, but you seem to have stuck it all in one commit making it very hard to understand what is going on.

You also seem to be working on an old version of the source, if you have a look at your pull request it looks like it is trying to roll back a load of fixes to the core.js file (removing the _clearObjectPointers function and undoing some typo fixes).

you are using underscores in your function names, this is not the convention in extension files, please change the names to fit with the convention of the rest of the code.

All of your comments start with "3.5 AA" can you please remove this as when merged in with the source this will be irrelevant, i can see in the pull request which comments are new

Your ***_dropdownEnabledCheck *** function is related to the extension and so should be in the extension file, you also shouldn't need to pass the table element to it, all objects in Tabulator get passed a reference to the table when they are instantiated.

The class names you pass into the ***addMenuItem*** function, what are they for, they are vague, and likely to be reused elsewhere, please make sure class names reflect what they are to be used for.

In your ***column_drop_down*** your variables start with capital letters (eg MenuExpanded), please ensure that all variable names are in camelCase, StudlyCase should only be used for class prototypes.

In your ***column_drop_down*** extension you have a huge if else statement to go through all the possible menu types. you will notice in the other extensions they work by looking up types from an object  (see sort.js, filter.js, edit.js), it makes for cleaner code and allows for users to easily extend the extension using the existing extension mechanic.

In your ***column_drop_down*** extension you try and lookup DOM  elements using a ***find*** 
 function, the relevant elements should be stored in an array/object when created and access programatically, It is faster and more reliable, Tabulator should not be traversing the DOM to try and locate an element.

In your ***column_drop_down*** extension you manually adjust the frozen classes and states. DO NOT manually adjust anything do do with freezing on columns/cells, this should be handled through the frozen_columns extension ONLY, you should update the definition and redraw the table, if you try and manually fudge things the extension is no longer encapsulated in its own code and it makes it impossible to maintain the codebase in the future.

There are additional issues, but i think we need to work through this list first.

In order for this to be approved i am going to need you to do the following:

- make these changes on the latest codebase on the 3.4 branch
- do not roll back existing functionality
- adhere to the coding style of the existing codebase
- create commits for each function change you add/make (if you change how freezing works that is its own commit etc...)
- do not mix the purpose of the extensions, an extension is responsible for one thing only
- fix the issues outline above.

Would you be able to create a working demo of your code in [Code Pen](https://codepen.io/) and send me a link, i would like to see it working and setup in the way you had intended.

I hope this dosnt put you off, i think it is great that you want to help out and i love your idea, but Tabulator has 1000's of users and i have to ensure it has a solid code base, i will be happy to go over things in stages with you if you would like.

Cheers

Oli

**Comment by olifolkerd** [comment]
Could i suggest to make life easier on yourself that for now you limit the pull request to the header list functionality and we can look at the frozen column tweaks another day, i am already updating that part of the system as part of the 3.4 updates, so i would suggest just sticking to the header lists first

**Comment by AbsAlnaffakh** [comment]
Thanks for your feedback Oli.

Will get the bulk of this if not all done over the weekend in compliance with your guidelines but I'll try and get you a demo way before then.

Don't worry I was not putt off, I have been self teaching my self JS, CSS, JQuery, SCSS, HTML while trying to make modifications to Tabulator. which may explain a thing or two up until recently I have been mainly doing back end and desktop application development.

Best Regards,
Abs

**Comment by olifolkerd** [comment]
Hey @AbsAlnaffakh 

Hows it going? are you still up for contributing your idea?

Cheers

Oli :)

**Comment by AbsAlnaffakh** [comment]
Hi Oli,

I'm good thanks, you?

Yes I still plan on completing the contribution but I keep on spending all my extra time on overtime for a project I am working on at work. The project makes use of Tabulator so I won't be able to complete it prior to officailly contributing all the modifications I made. I will do so soon either this or next month.

Best Regards,
Abdullah


-------- Original message --------

**Pull request closed without merging**
