### PR TITLE
add function to get header filter value for a specified column

### PR DESCRIPTION
**Pull request by jjech**
open PR for feature request #2571

### CODE REVIEW

**Comment by jjech** [comment]
@olifolkerd I am trying to test my changes, but I have encountered some problems which is why I have not marked this as ready for review yet. Can you provide me with guidance on how to test my changes correctly?

Here is what I did so far:
# modify my local tabulator instance with changes to utilize the new code
# npm install https://github.com/jjech/tabulator/tarball/master
# verify that the changes from my two PRs are present in node_modules/tabulator-tables/src

I can see that my local tabulator-tables module source code has the changes from my two PRs, but when I run my app I get some errors that make it look like the changes are missing somehow. Does this have something to do with 'dist'? My local tabulator-tables 'dist' sources don't have my changes in them...

Here are the stack traces I'm getting in the browser:
getHeaderFilterValue
`index.js:1446 Ajax Load Error:  TypeError: recordTable.getHeaderFilterValue is not a function
    at Ajax.ajaxURLGenerator [as urlGenerator] (App.js:491)
    at tabulator.js:8162
    at new Promise (<anonymous>)
    at Ajax.defaultLoaderPromise (tabulator.js:8160)
    at tabulator.js:8062
    at new Promise (<anonymous>)
    at Ajax.sendRequest (tabulator.js:8054)
    at tabulator.js:17685
    at new Promise (<anonymous>)
    at Page._getRemotePage (tabulator.js:17654)
    at tabulator.js:17633
    at new Promise (<anonymous>)
    at Page.trigger (tabulator.js:17614)
    at tabulator.js:17410
    at new Promise (<anonymous>)
    at Page.setPage (tabulator.js:17404)
    at RowManager.filterRefresh (tabulator.js:2704)
    at success (tabulator.js:12681)
    at tabulator.js:12833
console.<computed> @ index.js:1446
(anonymous) @ tabulator.js:8076
Promise.catch (async)
(anonymous) @ tabulator.js:8075
Ajax.sendRequest @ tabulator.js:8054
(anonymous) @ tabulator.js:17685
Page._getRemotePage @ tabulator.js:17654
(anonymous) @ tabulator.js:17633
Page.trigger @ tabulator.js:17614
(anonymous) @ tabulator.js:17410
Page.setPage @ tabulator.js:17404
RowManager.filterRefresh @ tabulator.js:2704
success @ tabulator.js:12681
(anonymous) @ tabulator.js:12833
setTimeout (async)
searchTrigger @ tabulator.js:12832`

custom headerFilterLiveFilterDelay
`tabulator.js:5574 Invalid table constructor option: headerFilterLiveFilterDelay
Tabulator.initializeOptions	@	tabulator.js:5574
Tabulator	@	tabulator.js:5225
(anonymous)	@	App.js:481
(anonymous)	@	App.js:287
tryCatcher	@	bluebird.js:5963
Promise._settlePromiseFromHandler	@	bluebird.js:3736
Promise._settlePromise	@	bluebird.js:3802
Promise._settlePromise0	@	bluebird.js:3852
Promise._settlePromises	@	bluebird.js:3948
(anonymous)	@	bluebird.js:231
Promise.then (async)		
schedule	@	bluebird.js:5105
Async.settlePromises	@	bluebird.js:230
Promise._fulfill	@	bluebird.js:3880
Promise._resolveCallback	@	bluebird.js:3640
(anonymous)	@	bluebird.js:3706
plumbing.callback	@	plumbing.js:104
RP$callback	@	plumbing.js:41
self.callback	@	request.js:220
emit	@	events.js:136
(anonymous)	@	request.js:1249
emit	@	events.js:136
(anonymous)	@	request.js:1160
onceWrapper	@	events.js:229
emit	@	events.js:142
endReadableNT	@	_stream_readable.js:1030
afterTickTwo	@	index.js:31
push../node_modules/process/browser.js.Item.run	@	browser.js:167
drainQueue	@	browser.js:131
setTimeout (async)		
runTimeout	@	browser.js:43
push../node_modules/process/browser.js.process.nextTick	@	browser.js:156
nextTick	@	index.js:30
resume	@	_stream_readable.js:794
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_readable.js.Readable.resume	@	_stream_readable.js:785
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_readable.js.Readable.on	@	_stream_readable.js:751
push../node_modules/request/request.js.Request.onRequestResponse	@	request.js:1149
emit	@	events.js:136
push../node_modules/stream-http/lib/request.js.ClientRequest._connect	@	request.js:260
(anonymous)	@	request.js:159
Promise.then (async)		
push../node_modules/stream-http/lib/request.js.ClientRequest._onFinish	@	request.js:156
(anonymous)	@	request.js:64
emit	@	events.js:136
finishMaybe	@	_stream_writable.js:613
endWritable	@	_stream_writable.js:622
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_writable.js.Writable.end	@	_stream_writable.js:571
push../node_modules/stream-http/lib/request.js.ClientRequest.end	@	request.js:287
push../node_modules/request/request.js.Request.end	@	request.js:1643
end	@	request.js:628
(anonymous)	@	request.js:644
run	@	setImmediate.js:48
runIfPresent	@	setImmediate.js:83
onGlobalMessage	@	setImmediate.js:125
postMessage (async)		
registerImmediate	@	setImmediate.js:136
setImmediate	@	setImmediate.js:34
push../node_modules/request/request.js.Request.init	@	request.js:581
RP$initInterceptor	@	request2.js:36
Request	@	request.js:155
request	@	index.js:58
(anonymous)	@	App.js:283
tryCatcher	@	bluebird.js:5963
Promise._settlePromiseFromHandler	@	bluebird.js:3736
Promise._settlePromise	@	bluebird.js:3802
Promise._settlePromise0	@	bluebird.js:3852
Promise._settlePromises	@	bluebird.js:3948
(anonymous)	@	bluebird.js:231
Promise.then (async)		
schedule	@	bluebird.js:5105
Async.settlePromises	@	bluebird.js:230
Promise._fulfill	@	bluebird.js:3880
Promise._resolveCallback	@	bluebird.js:3640
(anonymous)	@	bluebird.js:3706
plumbing.callback	@	plumbing.js:104
RP$callback	@	plumbing.js:41
self.callback	@	request.js:220
emit	@	events.js:136
(anonymous)	@	request.js:1249
emit	@	events.js:136
(anonymous)	@	request.js:1160
onceWrapper	@	events.js:229
emit	@	events.js:142
endReadableNT	@	_stream_readable.js:1030
afterTickTwo	@	index.js:31
push../node_modules/process/browser.js.Item.run	@	browser.js:167
drainQueue	@	browser.js:131
setTimeout (async)		
runTimeout	@	browser.js:43
push../node_modules/process/browser.js.process.nextTick	@	browser.js:156
nextTick	@	index.js:30
resume	@	_stream_readable.js:794
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_readable.js.Readable.resume	@	_stream_readable.js:785
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_readable.js.Readable.on	@	_stream_readable.js:751
push../node_modules/request/request.js.Request.onRequestResponse	@	request.js:1149
emit	@	events.js:136
push../node_modules/stream-http/lib/request.js.ClientRequest._connect	@	request.js:260
(anonymous)	@	request.js:159
Promise.then (async)		
push../node_modules/stream-http/lib/request.js.ClientRequest._onFinish	@	request.js:156
(anonymous)	@	request.js:64
emit	@	events.js:136
finishMaybe	@	_stream_writable.js:613
afterWrite	@	_stream_writable.js:470
afterTick	@	index.js:48
push../node_modules/process/browser.js.Item.run	@	browser.js:167
drainQueue	@	browser.js:131
setTimeout (async)		
runTimeout	@	browser.js:43
push../node_modules/process/browser.js.process.nextTick	@	browser.js:156
nextTick	@	index.js:47
onwrite	@	_stream_writable.js:458
WritableState.onwrite	@	_stream_writable.js:171
push../node_modules/stream-http/lib/request.js.ClientRequest._write	@	request.js:268
doWrite	@	_stream_writable.js:408
writeOrBuffer	@	_stream_writable.js:397
push../node_modules/stream-http/node_modules/readable-stream/lib/_stream_writable.js.Writable.write	@	_stream_writable.js:315
push../node_modules/request/request.js.Request.write	@	request.js:1623
end	@	request.js:610
(anonymous)	@	request.js:644
run	@	setImmediate.js:48
runIfPresent	@	setImmediate.js:83
onGlobalMessage	@	setImmediate.js:125
postMessage (async)		
registerImmediate	@	setImmediate.js:136
setImmediate	@	setImmediate.js:34
push../node_modules/request/request.js.Request.init	@	request.js:581
RP$initInterceptor	@	request2.js:36
Request	@	request.js:155
request	@	index.js:58
(anonymous)	@	index.js:66
(anonymous)	@	App.js:278
loadServerFile	@	App.js:276
rowClick	@	App.js:385
(anonymous)	@	tabulator.js:3858`

Thanks for your time and patience.

**Comment by jjech** [comment]
I think to resolve the issues described above I need to follow the instructions here to build dist:
http://tabulator.info/docs/4.1/install#setup-custom

I'm currently getting an error with Browserslist when running gulp, so hopefully once I resolve that I will be able to test my changes and mark as ready for review.

**Comment by jjech** [comment]
After successfully building and testing my changes, everything seems to be working as expected and I feel comfortable marking the PR ready for review.

**Comment by olifolkerd** [comment]
Hey @jjech 

Thank you for submitting your PR.

I have to say this is one of the cleanest PR's i have received in ages. it does exactly as specified and uses the same design patterns as the rest of Tabulator so thank you!

I will merge this into the 4.6 branch now and include it in the release in a few weeks time.

Please let me know if you would be up for contributing more in the future!

Cheers

Oli :)

**Pull request merged**
