### PR TITLE
Draft unit test

### PR DESCRIPTION
**Pull request by angeliski**
Hey @olifolkerd 
That is a first draft to #2054

Can you provide feedbacks?
You can see the travis build here: https://travis-ci.org/angeliski/tabulator/builds/596233421

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @angeliski 

Very Exciting!

Looking food so far, it seems to have some basic tests in place, so next up i guess we need to define a series of test cases to be included?

Do you have an recommendations?

Cheers

Oli :)

**Comment by angeliski** [comment]
Hey @olifolkerd 
I put only a simple test case, just to run the pipeline.
The better way is make the test run a file per module, we can think about the test cases to run in priority and develop the others on demand.

**Comment by angeliski** [comment]
@olifolkerd A question, nowadays you use the gulp to inject the files, like ```/*=include column_manager.js */```

You see any problem if we translate that to CommonJS(using module.exports) and using something like webpack/browserify to make the build?

My question is just because the current files don't have the module.exports, so we can't require that in the test file.

That will fail:
```
const ColumnManager = require('../src/js/column_manager');
```
What do you think?

**Comment by olifolkerd** [comment]
It is done that way because the there are different combinations of files pulled in for the different modules.

I'm not sure why you would need to change it. The modules can't be run independently they have to be included with the table so surely the tests should run on the compiled dist files.

**Comment by angeliski** [comment]
Hey @olifolkerd Sorry the late response, I was working in another thing

I was understanded the modules can't be run independently, but when you think about unit tests, the expect is module's test  in a isolated enviroment. We can add a integration layer to  catch any error on use the modules inside the tabulator, but is nice test the module in a unit test first. Does it make sense?

I proposed that change because we need a way to test each module, like module.exports or maybe export default.

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thanks for the additional information.

Im not against moving to this, but there is a lot that needs to be through through first. there are many versions of dist JS files build from the src files. not just the minified files. For example there is the option to use the core.js module and then install each module individually on your site.

In that instance the require syntax would be invalid as it could not be handled in browser an on IE. so if this is the way we need to move then we need to consider the whole packaging process further.

more information on the packaging options can be found [Here](http://tabulator.info/docs/4.4/install)

Cheers

Oli :)

**Comment by angeliski** [comment]
Hey @olifolkerd 
Make sense, if we choose to move to CommonJS we need to build another output, using something like  webpack or browserify.

Can I work in a draft for that?

**Comment by rotht2** [comment]
Hello, we are also interested in unit tests with Tabulator. Are there any updates on this? I recently spiked getting Jest working and I ran into the same issues that @angeliski had.

**Comment by olifolkerd** [comment]
@angeliski Sorry for the delay in getting back to you, my father passed away at the end of November so i haven't been terribly focused on things the last month.

I can't see why you would need to move away from gulp to support this. it is a task automation tool, it will do what you ask it too.

in version 4.6 we are moving to gulp4 which provides even better support.

I would be reluctant to move to another automation tool unless you can provide some very clear advantages as to why this would be needed.

Cheers

Oli :)

**Comment by jjech** [comment]
@olifolkerd really sorry to hear about your father's passing.

One benefit to moving away from gulp is this would eliminate the dependency on the deprecated gulp-cssnano package, which has broken the build process as explained in issue #2581.

But we can use npm shrinkwrap as shown in PR #2582 or the manual workaround to continue building with gulp at the moment, so it doesn't really seem to be much of a problem.

**Comment by olifolkerd** [comment]
Hey,

Are you still interested in making some unit tests now that version 5.0 is most ready?

Oli

**Pull request closed without merging**
