### PR TITLE
Issue #2064 row.update() doesn't seem to update child/sub values.

### PR DESCRIPTION
**Pull request by aklaver**
Modify row.js to descend into nested data on row.update() and update the cells.
I am still relatively new to Javascript, so suggestions as to applicability of this code are welcomed.  The comments inline explain what I am doing.

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @aklaver 

Im a bit unsure as to the usage case of this. if you update the ***_children*** property of a row with the ***update*** function it already refreshes the child rows?

What am i missing?

Cheers

Oli :)

**Comment by aklaver** [comment]
This is not for Data Tree:
http://tabulator.info/docs/4.2/tree
but for nested data in a field:
http://tabulator.info/docs/4.2/columns#field-nesting
See:
https://github.com/olifolkerd/tabulator/issues/2064

**Comment by olifolkerd** [comment]
Ahh with you now.

There is actually already a system for handling this built into the column management system (it is a smidge more complicated than exploding on the "." as tabulator allows for custom delimiters and other such fun).

You have definitely spotted an area that needs improvement, but it actually should only take a line of code to tie it into the correct part of the system.

I will make a commit with the fix in tomorrow and post a link to it here so you can see how it is done incase you come across any others like it.

Cheers

Oli :)

**Comment by aklaver** [comment]
Did you ever make the change above? If so can you point me at it. Thanks.

**Comment by psmitty7373** [comment]
I am suffering form this same issue, updateRow is failing to update fields that are object properties.  Redraw works, but causes other issues for me.

**Comment by olifolkerd** [comment]
@psmitty7373 

Please post a JS Fiddle that demonstrates your issue and we can offer you some advice.

If you feel this is a new issue please create a new issue.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Ahhhhh I have just finally cottoned on to what it was you are trying to achieve here.

Yes that was definitely a needed change.

Looking at your proposed solution it was a bit verbose and revolved around build an array that already exists in the column manager and then it only handled one level of nesting, where there are already systems built into the columns objects to handle data management of nested data.

I have just pushed a fix for this to the master branch and will include it in a patch release today.

Cheers

Oli :)

**Pull request closed without merging**
