### PR TITLE
Cell selection working and copying headers

### PR DESCRIPTION
**Pull request by nl095059**
From a look and feel point of view I have tested this against the materialize theme, but not the others at the moment. I have been using jest locally to unit test, but have omitted it from this PR as I see you are hoping to get a test framework into the 5.0 release and don't want to conflict with that effort.
I have tried to keep these changes relatively isolated in the select_cell module, but feel free to pick me up on omissions/issues/required tidying as I am still very new to the tabulator framework.

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @nl095059 

Thanks for your PR, it is always great to see people looking to contribute to Tabulator.

Sadly your PR couldn't have come at a worse time. the 5.0 release which I am just about to start work on will include a complete rebuild of the core library, with a new Cellular VDOM that will bring in a host of new spreadsheet functionality like row/column spans, cell range definitions and cell selection. Which will i am afraid not be compatible with this PR.

Had it been submitted even a week earlier it may have been able to been included in the last of the 4.x releases.

Im unsure what you mean by copying headers in your PR. It is usual to submit a PR with only one update to prevent multiple updates being held up with the review of each PR.

It would be great to see you involved with Tabulator contributions again, Could i ask that if you are looking to make a big contribution like this that you discuss it on the issues list first, it helps to coordinate peoples efforts and would avoid scheduling issues like this one.

Cheers

Oli :)

**Comment by nl095059** [comment]
Hi Oli,

  I figured it might have landed at just the wrong time, but thought I would put up my effort in the meantime to encourage discussion about the feature/implementation, etc.
As for the headers, I just mean that when you select a range of cells and press ctrl-c, then it will put both the relevant headers and cells into the clipboard text (Similar to how the row selection works, but limiting to the relevant columns).

I will happily try and re-implement any elements of this PR that don't exist in the 5.0 codebase. Do you have any idea currently as to when you will be able to make this branch public?

Awesome library btw.

**Comment by xinxilas** [comment]
Does the current 5.1 version already has this new cell based vdom?

@nl095059 can you kindly make your changes on the latest 4.x version and publish in a temporary forked repo?

**Comment by rathboma** [comment]
@nl095059 @olifolkerd did cell and cell-range selection become part of the 5.x release branch? If not I'm happy putting it on my todo list, as this is definitely something I need.

**Comment by olifolkerd** [comment]
@rathboma It did not, if you would like to add it i would happily accept a PR for the functionality. Wanna have a chat through the possible options?

**Comment by rathboma** [comment]
@nl095059 I've downloaded your branch to play around with it, but I can't seem to enable the module. Do you have a demo html file that you used for testing at all?

**Comment by rathboma** [comment]
Ok, I got it working. This def has promise, but having 12k open event listeners for a table isn't really doable.

@olifolkerd does the internal event bus in v5 have a way to let me detect cell mousedown/up events without adding new event listeners to every cell?

**Comment by olifolkerd** [comment]
Hey, 

Yeah, you shouldn't put any event listeners on components, that approach was changed in the 5.0 rebuild

 you should use the internal event bus to subscribe to the cell-mousedown event or cell hyphen whatever particular event you are interested in

There is a interaction manager in the core code that check for listeners and then binds a single listener to the table. It then works out the source of any interaction event and triggers an internal event passing the component for the element that was interacted.

Checkout the module docs for more details

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @rathboma 

Just a quick note The code in this PR is no longer compatible with the 5.0 architecture.

All functionality needed for this functionality would need to be included in its own module, not distributed across all the files used in this PR.

You would need to structure it with a cellular selection module, and then if you wanted to integrate it with clipboard add a clipboard selection range to that module.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@rathboma 

This explains more about how to build a module, how to bind functions to the table and component objects:
http://tabulator.info/docs/5.2/module-build


This explains how to use the internal event bus, from 5.0 onwards modules should only communicate with each other through the event bus if needed, legacy direct module calls between one another is being phased out with each release:
http://tabulator.info/docs/5.2/events-internal

This includes some examples of how to use the module functionality:
http://tabulator.info/docs/5.2/module-examples

and you can use the debug tools to monitor the internal event bus to see when events are fired:
http://tabulator.info/docs/5.2/debug

Let me know if you need any more info

Cheers

Oli )

**Comment by rathboma** [comment]
Thanks Oli! Yeah I'm going to have to re-write this code from scratch, I just wanted to preview it to see if it worked.

Have you considered having a 'test' or 'example' folder in the repo with a bunch of pre-configured html templates for during development?

**Comment by olifolkerd** [comment]
Not sure I follow you there @rathboma, what sort of templates are you thinking of? The docs site has a load of example code on it already?

**Comment by tobiasBora** [comment]
Any news on this feature? I’d love to have it.

**Pull request closed without merging**
