### PR TITLE
Fix issue #2524 + fix typo setNestedData function

### PR DESCRIPTION
**Pull request by lorpmtp**

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @lorpmtp 

Thanks for your pull request.

Please can you include a description with your pull request that explains what you are trying to achieve and the method you have taken. please also bear in mind that you need to take into account all uses of a function when making an update.

There is an issue with your current approach, if someone calls the ***setValue*** function on a cell component and for a cell whos current value is undefined then the current version of this function  works exactly as it needs to because it would need to create the series of nested objects to set the value on the cell. your proposed update would break this.

There are a few structural issues with the commit that need to be resolved before i can accept this:
- you have included updates to the css files and map files in your commit that are totally unrelated to your changes. please only include the files you have actually update
- the comparison in the if should be if the type of the variable is undefined not if the variable is null
- the closing bracket on line 773 is not correctly indented 

If you can fix the structural issues in the commit and address my concerns about the setValue issue then i would be happy to proceed with this.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
A simple way of achieving what you are after is to check if the value variable comming into the function is undefined and then handling it differently

**Comment by lorpmtp** [comment]
Hi Oli !

Thx for your return on this.

I effectively need to check whether the type is undefined or null depending the case.

Cheers

**Comment by olifolkerd** [comment]
As I mentioned in my above reply, your current approach is flawed and breaks other parts of the table.

Pull requests must account for all uses of the table and not break the table for others.

I will be unable to accept this PR unless you can fully address the issues outlined in my initial response.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @lorpmtp 

Are you interested in resolving the issues or shall i close this PR?

Cheers

Oli :)

**Comment by lorpmtp** [comment]
I plan to fix it this week. Happy new year !

**Pull request closed without merging**
