### PR TITLE
fix movable columns and range selection

### PR DESCRIPTION
**Pull request by azmy60**
This PR should allow us to have movable columns and also column range selection. Currently, enabling both options would results in weird behavior.

DEMO (to replicate): https://jsfiddle.net/4pqox6gu/

mygif

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @azmy60 

Looking good there, one quick tip on naming, the Tabulator convention is to use "ing" for when a thing starts and "ed" for when it ends

so it would be `column-moving` and `column-moved` if you would be ok with the changes. There is already an existing `column-moved` event, would the exiting one work for you without needing your new one? it is triggered at about the same time, just from a different point in the code?

Cheers

Oli :)

**Comment by azmy60** [comment]
Hey @olifolkerd ,

Yeah, that's fine. The code still works with the existing event.

**Comment by marsrover4** [comment]
could someone please merge this? 0:)

**Comment by marsrover4** [comment]
Thanks for the merge! :)

**Pull request merged**
