### PR TITLE
If the cell value is an array do not stringify it, instead use the ar…

### PR DESCRIPTION
**Pull request by rotht2**
Updated PR with isolated changes supporting cell formulas.

This puts the requirement on the user to format their data how they wish for it to be displayed when using an array.

### CODE REVIEW

**Comment by rotht2** [comment]
#2648

**Comment by olifolkerd** [comment]
Hey @rotht2 

Following on from our earlier discussion about making this an optional feature and not breaking existing functionality for users who simply want to use arrays, i have a proposed solution.

Let us keep the exsiting functionality as it is but add a property to the config object passed in to the third argument of the download function that enables your new regex functionality, something like ***regexArrays***

How does that sound?

Cheers

Oli :)

**Comment by rotht2** [comment]
Just wanting to clarify, you are thinking that we would pass a "feature flag" into the config object which will drive the ability to pass the array into SheetJS vs a stringified version of the array?

You mentioned Regex which confuses me a little.

**Comment by olifolkerd** [comment]
Hey sorry for the confusion.

I didn't mean regext at all, I was meaning the formula. Pick a config property name that makes sense.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @rotht2 

Did you manage to get any further with this. im looking to do a release for the 4.7 branch next week and i would love to include this in it.

You would probably need to resubmit as a PR against the 4.7 branch as the module has been completely rebuilt for the 4.7 release.

Cheers

Oli :)

**Comment by rotht2** [comment]
Hey Oli,

Sorry for the delay in response, I have not gotten around to it yet. Life has been pretty busy for me and I haven't had a lot of extra time to bang out some code. It's on my list. Thanks for the update

**Comment by olifolkerd** [comment]
Closing this due to a lack of activity, if this is something you are still interested in please create a new PR against the latest code on the master branch.

Cheers

Oli :)

**Pull request closed without merging**
