### PR TITLE
Break expanded range after pressing arrow keys

### PR DESCRIPTION
**Pull request by azmy60**
**To reproduce:**
- Select all cells by pressing `Ctrl+Shift+Arrow`
- Press Up Arrow without `Ctrl+Shift`

**Expected:** Only one cell should be selected and it appears in the view
**Actual:** It does nothing

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @azmy60 

Thanks for this suggestion, id be happy to include this, but as ive mentioned before the coding style for Tabulator does not allow for getter properties.

If you would move the rowHeaderWidth getter into a function i would be happy to include it.

Cheers

Oli :)

**Comment by azmy60** [comment]
@olifolkerd Thanks for the feedback! Just fixed the getter and merge conflict as well.

**Comment by azmy60** [comment]
Hey @olifolkerd ! Would you take a look when you have time to review this? Thanks! :)

**Comment by olifolkerd** [comment]
Hey @azmy60

Thanks for the update there, i will include it shortly in the 6.3 release.

Cheers

Oli :)

**Pull request merged**
