### PR TITLE
Update tabulator_bootstrap.css

### PR DESCRIPTION
**Pull request by iceman60**
Mistype

### CODE REVIEW

**Comment by lavigor** [comment]
Why so many PRs for a single purpose?
Even if you use web interface, you can create several commits for one PR.
Using descriptive titles and commit messages also helps other contributors in understanding the changes.

**Comment by iceman60** [comment]
Sorry, I'm new with Github, I didn't know we can create several commit for one PR...
Maybe someone can merge the PR or tell me how to do that?

**Comment by lavigor** [comment]
@iceman60 the thing is that you cannot hide/delete PRs or merge them together.
You can only start a new one/make rebases/rename them.

**Comment by olifolkerd** [comment]
Hey @iceman60 

Thanks for getting in touch, 

Good spot on the typo there, but Im afraid i cannot accept pull requests on css files as they are all automatically generated by gulp. i can only accept stylesheet changes if they are made on the .scss files in the /src/scss directory. Changes anywhere else will just be overwritten when the css files are next regenerated.

I also agree with @lavigor these should all be in one pull request otherwise the commit log will be jammed up with loads of merges to fix the same issue.

Because of this i am going to close your currently open Pull requests, but if you could submit one pull request with the changes made to the files in the /src directory then i would be happy to accept it.

Cheers

Oli :)

**Pull request closed without merging**
