### PR TITLE
[WIP] - Draft to select row input feature 

### PR DESCRIPTION
**Pull request by angeliski**
Hey @olifolkerd 

That is the PR for #2229 
I made a more simple possible. Now we can talk about the solution. You can see in the bellow the visual result.
tabulator-checkbox

See you

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey, great first start.

So a bit of feedback.

 You will need to handle clicking on the input to toggle row selection
because a lot of users turn of selection by clicking on the row as a whole.
You will just need to stop the click propagating from the input to the row
to prevent it from immediately untoggling itself.

In the select row module where you are changing the checked state of the
element you will need to check it has been set, other wise it will break
row selection without the formatter.

Looking good so far.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey, great first start!

So a bit of feedback.

You will need to handle clicking on the input to toggle row selection because a lot of users turn of selection by clicking on the row as a whole. You will just need to stop the click propagating from the input to the row to prevent it from immediately untoggling itself.

In the select row module where you are changing the checked state of the element you will need to check it has been set, other wise it will break row selection without the formatter.

in your formatter when you are calling ***registerRowSelectChecbox*** *(which there is a typo in :p, it should be check not chec)* you should wrap the line in the following if statement, which checks to see if the selectRow module is installed before running the function, and warns the user if it isnt. this is needed because there are slimmed down ways to use Tabulator without all the modules installed, so all calls to module functions are guarded this way
```js
if(this.modExists("selectRow", true)){
    ///call function on the module
}
```
Looking good so far.

Cheers

Oli :)

**Comment by angeliski** [comment]
Fixed @olifolkerd 

Let me know any problem and thanks for your feedback

**Comment by olifolkerd** [comment]
Hey @angeliski 

Looking good so far, 

I like the aria tagging in the formatter, great idea, but it isnt actually needed if you are using an input of type checkbox, it is only needed to tell a screen render that if you are using non standard tags. but this might come in useful for your svg formatter idea, which we can come onto shortly

So onto the fun bit, the title formatter!

so the ***titleFormatter*** param takes the same formatter as the ***formatter*** param. so we are going to use our same formatter to do two different jobs depending on where it is used.

title formatters work by passing in a pusdo cell component that mimics a normal cell component to provide access to the header element, but importantly it is lacking a ***getRow*** function. so in your formatter, if you use an in statement on the `typeof cell.getRow == 'function'` you can then put the cell formatting code in that and the header formatting code in the else.

so in this case we want to create another function in the selection module, lets call it ***registerHeaderSelectCheckbox***, and pass in the checkbox element. we then want to store this on a variable set in the module, lets call it ***headerCheckboxElement***.

Then in the ***_rowSelectionChanged*** function if the ***headerCheckboxElement*** is set we want to check that the number of rows in the ***selectedRows*** array is equal to the number of rows on the `this.table.rowManager.rows` array, if it is equal the check box should be checked, if it is empty the tickbox should be unticked, and if it is greater than zero but less than the number of rows then it should be set to an indeterminate state with `headerCheckboxElement indeterminate = true`.

You will also need to decide what happens when a user clicks on a checkbox that is in an indeterminate state.

Let me know if that all makes sense.

Cheers

Oli :)

**Comment by angeliski** [comment]
Nice @olifolkerd 
I need spend some time in other urgents issues, but I will retake in monday, ok?

See you

**Comment by olifolkerd** [comment]
All good, I'm looking to release in a couple of weekends time, so as long as we can get it finished by next Friday it will make the 4.4 release

**Comment by angeliski** [comment]
Hey @olifolkerd I make the header works

Let me know any problem

See you

**Comment by olifolkerd** [comment]
Hey @angeliski 

Great work, i think we are almost there, i look forward to being able to include it in this sundays release.

So a couple of tweaks remain:

- in the formatter, you probably want to change the event listener from ***click*** to ***change*** to handle scenarios where the user has tabbed to the tickbox and changed it with an enter or space key

- in your _rowSelectionChanged logic if you change the order of the if statements you can avoid setting the indeterminate property twice. make your if else the if and remove the first if statement, then take the logic from the first if statement and put it inside the else to set the indeterminate true or false.

Then i think we should be all there! great work!

Once those changes are in i will merge it into the 4.4 branch. Once that is released we can work through adding the SVG option if you like.

Cheers

Oli :)

**Comment by angeliski** [comment]
Hey @olifolkerd you  can move the release to monday? I stay in a trip away from my computer and will return soon to fix that comments

**Comment by olifolkerd** [comment]
Hey @angeliski 

No chance im afraid, i have a busy week ahead so sunday afternoon is the latest i can push it.

I am happy to merge things in as they stand and make the last couple of updates myself, then leave it up to you to put in the next set of updates.

Cheers

Oli :)

**Comment by angeliski** [comment]
OK @olifolkerd 
We keep improve that in other releases.
Thank you for help

**Pull request merged**
