### PR TITLE
getGroupedData- clean

### PR DESCRIPTION
**Pull request by resonatingfury**
@olifolkerd 

Thank you once again for the tips and pointers- I was a little out of it last night and put some weird logic through. The only issue I ran into while cleaning the code up was an error with `row.getRows(true)`.

image

I'm not sure if this is specific to my dataset or not, but I left the code as just `row.getRows()` which produces the data correctly for me.

### CODE REVIEW

**Comment by olifolkerd** [comment]
Great news, 

sorry that was my bad, it should have been `row.getData("data")` which tells the system to apply the data accessor tranforms to the data before it leaves the table.

Could more bits of feedback for you, almost there now.

You are defining, groupListData as an array but then assigning values to properties on it like it is an object the line below.

could you make sure you define your variables first then perform actions on them, at the moment the self var is defined after the a assignment, also just out of preference if you use a self var, could you make it the first one in the list.

Aside from that it is looking great,

Cheers

Oli :)

**Comment by resonatingfury** [comment]
Hi @olifolkerd,

Thanks for all of your patience throughout this process- I'm taking in a lot of this! I think now it should be good to go :)

**Comment by olifolkerd** [comment]
Hey @resonatingfury 

Thanks for that, it looks really good. Pull requests are always collaborative so your welcome. There is a lot of added complexity to the internal workings of Tabulator so i don't expect people to be able to jump straight it.

I will look at merging this in in a week or two when i merge in the 4.1 branch for the next release.

Thanks for your contribution, let me know if you want to do any more in future.

Cheers

Oli :)

**Comment by resonatingfury** [comment]
@olifolkerd 

Awesome! Happy to help :) I'd be glad to contribute further, if you need anything, definitely let me know and I'd work on it when I can!

**Comment by olifolkerd** [comment]
All merged in!

Thanks for your contribution :D 

Im going to be posting some help needed issues in the next few days, so if your interested in contributing some more, keep an eye out for those.

Cheers

Oli :)

**Pull request merged**
