### PR TITLE
Issue  #2258. ReferenceError in RowManager.prototype.redraw when global `self` is not defined.

### PR DESCRIPTION
**Pull request by aklaver**
Issue #2258 
Add self = this in redraw() when in 'classic' renderMode.

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hi @aklaver 

Thanks for the input, i like the idea for the test, but could i ask that you tweak your implementation a bit:

- could you move your test function onto the prototype to be consistent with other function calls
- could you set the property "_tabulator_test" instead of just "test" as it will reduce the chance of accidentally overwriting something outside of the scope of Tabulator.
- when calling functions on the window object please explicitly use `window.` as it makes it clear what the scope should be

If you can make those changes i would be happy to accept the PR.

Cheers

Oli :)

**Comment by aklaver** [comment]
I'm guessing you are referring to my other PR(https://github.com/olifolkerd/tabulator/pull/2280). I will look at the above and make the changes.

**Comment by olifolkerd** [comment]
My Bad, i had too many tabs open lol

**Comment by olifolkerd** [comment]
There is no need to set the self variable in this function, just rename any uses of self in the function to ***this***

It will have been caused by a copy and paste error from inside a callback written before i started introducing arrow functions into the code base

Cheers

Oli

**Comment by aklaver** [comment]
Got it.

**Pull request merged**
