### PR TITLE
Add Require and Import Values in `package.json` for better `ESM` Support

### PR DESCRIPTION
**Pull request by thisjt**
`build/Bunder.mjs` has been changed so that `tabulator_esm` output in `dist/js` will have the `.mjs` extension.

`package.json` has been changed so that the file that the bundler creates is properly referenced.

Referencing bug report: https://github.com/olifolkerd/tabulator/issues/4378

### CODE REVIEW

**Comment by dominikg** [comment]
thanks for working on improving esm compatibility :heart: 

Please keep in mind that adding an exports map is almost always a breaking change and you have to list all exports that are needed.

**Comment by olifolkerd** [comment]
@dominikg do you want to clarify this further? Possibly with any examples of areas of specific concern there?

**Comment by olifolkerd** [comment]
@thisjt could you revert the change to the bundler please and only include the e package change. Plenty of people still use the .js file directly when pulling from cdns so the .js file cannot be removed without disabling a huge number of users. Instead I will make the bundler duplicate the output to the new extension and deprecate the .js and remove it at the next major version change in a year or two to give people a chance to adapt

**Comment by thisjt** [comment]
@olifolkerd done. You may review the changes and then take over from there.

**Comment by dominikg** [comment]
I don't know the details behind the current structure of this package, just provided links to information how to make this esm compatible. Most ways to do this are a breaking change due to the way it changes how exports of your package can be reached. Without an exports map, everything that is exported can be imported by users. With an exports map, only the entries in the exports map can. publint and the guide by antfu go into more detail about this.

**Comment by olifolkerd** [comment]
@thisjt is the exports bit actually needed? If you point the modules option to the .mjs file does it work in sveltkit?

**Comment by thisjt** [comment]
@olifolkerd yes I assume it's required.

This repo (https://github.com/thisjt/tabulator-import-issue/tree/rename-import) imports (https://github.com/thisjt/tabulator-sveltekit2fix/tree/tabulator-import-rename). This throws an error. This is what its `package.json` looks like.
```
...
  "main": "dist/js/tabulator.js",
  "module": "dist/js/tabulator_esm.mjs",
  "sideEffects": [
    "**/*.css",
    "**/*.scss"
  ],
...
```

This repo (https://github.com/thisjt/tabulator-import-issue/tree/rename-import-with-exports) imports (https://github.com/thisjt/tabulator-sveltekit2fix/tree/tabulator-import-with-exports). This works fine and the table is being rendered correctly. This is what its `package.json` looks like.
```
...
  "main": "dist/js/tabulator.js",
  "module": "dist/js/tabulator_esm.mjs",
  "exports": {
    ".": {
      "require": "./dist/js/tabulator.js",
      "import": "./dist/js/tabulator_esm.mjs"
    }
  },
  "sideEffects": [
    "**/*.css",
    "**/*.scss"
  ],
...
```

**Comment by olifolkerd** [comment]
Hey All,

This will be included in todays patch release.

Cheers

Oli :)

**Comment by lazka** [comment]
fyi, this removed the export for the package.json file which made my build fail (I haven't looked in detail yet):

```
[!] Error: Package subpath './package.json' is not defined by "exports" in /home/runner/work/app/app/node_modules/tabulator-tables/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:590:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:664:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1126:27)
    at Function.resolve (node:internal/modules/helpers:188:19)
```

**Comment by thisjt** [comment]
> fyi, this removed the export for the package.json file which made my build fail.
> 
> I used the path to package.json to figure out where the CSS is to copy that during bundling. I guess I can use the default import and go up the directory tree until I find the package.json instead. Other ideas welcome :)
> 
> ```
> [!] Error: Package subpath './package.json' is not defined by "exports" in /home/runner/work/app/app/node_modules/tabulator-tables/package.json
>     at new NodeError (node:internal/errors:405:5)
>     at exportsNotFound (node:internal/modules/esm/resolve:366:10)
>     at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
>     at resolveExports (node:internal/modules/cjs/loader:590:36)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:664:31)
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1126:27)
>     at Function.resolve (node:internal/modules/helpers:188:19)
> ```

We might need to add this to `package.json` to fix the import css issue. I haven't really encountered this issue as I am importing the css file through `node_modules` (which is a bad practice I know, but I haven't bothered touching it since 2~ years ago)

```json
"exports": {
    ".": {
      "require": "./dist/js/tabulator.js",
      "import": "./dist/js/tabulator_esm.mjs"
    },
    "./dist/*.css": {
      "import": "./dist/*.css",
      "require": "./dist/*.css"
    }
}
```

https://github.com/vitejs/vite/discussions/2657

**Comment by olifolkerd** [comment]
@thisjt Thanks for the headsup, ive just made an updated patch release on 6.2.3. let me know how that works for you.

Cheers

Oli :)

**Comment by thisjt** [comment]
> fyi, this removed the export for the package.json file which made my build fail.
> 
> I used the path to package.json to figure out where the CSS is to copy that during bundling. I guess I can use the default import and go up the directory tree until I find the package.json instead. Other ideas welcome :)
> 
> ```
> [!] Error: Package subpath './package.json' is not defined by "exports" in /home/runner/work/app/app/node_modules/tabulator-tables/package.json
>     at new NodeError (node:internal/errors:405:5)
>     at exportsNotFound (node:internal/modules/esm/resolve:366:10)
>     at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
>     at resolveExports (node:internal/modules/cjs/loader:590:36)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:664:31)
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1126:27)
>     at Function.resolve (node:internal/modules/helpers:188:19)
> ```

Can you confirm if this works on your end @lazka? Try editing `node_modules/tabulator-tables/package.json` and modify the exports to look like this

```json
  "exports": {
    ".": {
      "require": "./dist/js/tabulator.js",
      "import": "./dist/js/tabulator_esm.mjs"
    },
	"./dist/*.css": {
		"import": "./dist/css/*.css",
		"require": "./dist/css/*.css"
	}
  },
```

Then try importing the css in your scss stylesheet like this
```scss
@import 'tabulator-tables/dist/tabulator_site.css';
```

Oli has not published `6.2.3` yet, but this would be the expected edit for the export. Hopefully it will now work on your end.

---

@olifolkerd since `6.2.3` is not yet out, would it be possible to also add this to the exports? It would be nice to be able to import scss stylesheets directly from the package and take advantage of modifying the scss variables.

```json
  "exports": {
    ".": {
      "require": "./dist/js/tabulator.js",
      "import": "./dist/js/tabulator_esm.mjs"
    },
	"./dist/*.css": "./dist/css/*.css",
	"./src/scss/**/*.scss": "./src/scss/**/*.scss"
  }
```

So that the scss files can be imported~
```scss
// like this
@import 'tabulator-tables/src/scss/themes/tabulator_site.scss';

// instead of this
@import '../../node_modules/tabulator-tables/src/scss/themes/tabulator_site.scss';
```

The css and scss exports can be simplified as shown above as they are not affected on whether you're loading them in ESM, UMD, or CJS as per https://github.com/vitejs/vite/discussions/2657#discussioncomment-10050134

Or maybe I can raise a new PR for this.

**Comment by lazka** [comment]
> Can you confirm if this works on your end @lazka?

The package.json export is still missing in your example (as in `"./package.json": "./package.json"`) , so I doubt it changes anything. And I'm not using SCSS.

Anyway, I solved it already via the workaround described above: https://github.com/digital-blueprint/toolkit/commit/47d250d945d11a5f9997cddfb5d764a49f36ea60

So feel free to ignore my use case :)

Thanks for asking!

**Comment by dominikg** [comment]
as mentioned earlier, adding an exports map was a breaking change. not just for the reported package.json, but everything in src is now inacessible too. 

should have published it as 7.0

**Comment by olifolkerd** [comment]
@dominikg could you explain what you are trying to access in src, none of those files are safe to include for production runs?

**Comment by olifolkerd** [comment]
The same could be said if I change an internal variable name. But I don't expect people to do that and I don't update the major version for that either.

I would consider it a change in behaviour if it breaks expected standard documented behaviour which this doesn't, and if access to the src folder is important then I am more than happy to do a patch release with a wildcard export for that folder to make it accessible again making this a non breaking change :)

**Comment by dominikg** [comment]
It is your package and you know your users better than I do. I'd caution against adding a glob in exports map as they bring back the problem you just described yourself. every rename or delete of a file matched by that glob would be a breaking change again. So the exports map limited to dist gives you a lot more freedom internally, you should keep it that way.

**Pull request merged**
