### PR TITLE
Add row.isTreeExpanded

### LINKED ISSUE #3288: Persistent column order for generated columns
**Describe the bug**
Persistent column order does not work for columns which have no `field` option but are generated via formatters.

**Tabulator Info**
- 4.9.3

**Working Example**
https://jsfiddle.net/1qjvbf30/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

1. Move the Id column to a new position
2. Run the Fiddle again
3. The column will move back to its original position

**Expected behavior*
Column order should stay the same between reloads

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 90.0.818.46

### PR DESCRIPTION
**Pull request by PeterShinners**
Adds boolean method to row and datatree to determine if a row is expanded or collapsed.

Fix #3288

### CODE REVIEW

**Comment by PeterShinners** [comment]
I'd like to update the documentation also, but not finding where that comes from.

**Comment by olifolkerd** [comment]
Hey,

Thanks for the PR, but I'm afraid I'm not accepting and PRs on the master branch at the moment.

The whole library is been completely rebuilt for the 5.0 release with a totally new way of handling component function bindings, which will not be compatible with the current approach.

I think you have a good idea there, but would suggest you hold off for a couple of weeks till the technical preview 5.0 alpha release is available and then make your PR against the 5.0 branch. The alpha release will include updates to the docs site to take people through how the new backend works.

The documentation isn't updatable on git. PRs that add functionality are only merged in with major or minor release versions and the docs are updated with each release.

Cheers

Oli

**Comment by PeterShinners** [comment]
Understood. Looking forward to the arrival of 5.0. I'll reattempt later.

**Comment by olifolkerd** [comment]
Hey @PeterShinners 

Version 5.0 has now been released, if you were still interested in submitting this feature.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This functionality is now being included in tomorrows 5.1 release.

Cheers

Oli :)

**Pull request closed without merging**
