### PR TITLE
make headerFilter typingTimer configurable

### PR DESCRIPTION
**Pull request by jjech**
See https://github.com/olifolkerd/tabulator/issues/2522

Please review carefully. Unsure how to test this, or if further changes are needed in order to fulfill the request. Looking forward to your feedback!

### CODE REVIEW

**Comment by jjech** [comment]
@olifolkerd please review when you have time. Happy holidays!

**Comment by olifolkerd** [comment]
@jjech please dont pressure me to review your pull request *(i have deleted your last post)*, i will get round to it in my own time.  if you have a look at the [Community Guidlines](http://tabulator.info/community) it clearly states that you should not chase to get action on your issue. 

> DO NOT chase feature requests by repeatedly asking "when will this be done". Issues are prioritized according to how popular they are with the user base, how simple they are to add, when they would fit into the existing Development Roadmap and may other factors. There are many open feature requests and only so much time available so please be patient. Some features may be added in the next release, others you may have to wait more than a year for.

I have to balance my own personal needs against the needs of 1000's of user and just because an issue is important to you does not mean it will get top priority from me.

As it is also states clearly in the guide lines the accepting of a pull request does not mean that it will be included in the master distribution straight away:

> Do not expect your code to be merged into the codebase straight away. In order to make sure that users are kept up to date with changes, PR's are only merged into the master branch when a new version of Tabulator is released and the documentation is updated. If your PR has been approved and is waiting for the next release it will be given the state of PR Awaiting Merge. Bug fixes are usually merged into patch releases which happen every week or two, feature updates will be included in minor releases which happen every 2 to 3 months`

So please bare with me, features will be reviewed and included in the release when i have the time to review them and when the time is right for a new release and not before.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @jjech 

Thanks for your PR. On the whole that looks good, but there are a couple of tweaks that need to be made before i can merge this in:

- it looks like you are referencing the table variable but it should be `this.table`
- could you rename the ***headerFilterTypingTimer*** option to ***headerFilterLiveFilterDelay*** to make it a bit more descriptive as that is what it relates to.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @jjech 

Thanks for making those changes.

I will merge this in and include it in the 4.6 release in a few weeks.

Cheers

Oli :)

**Pull request merged**
