### PR TITLE
feat: Add `!default` flag on every SCSS variable

### PR DESCRIPTION
**Pull request by dahfazz**
Following https://github.com/olifolkerd/tabulator/issues/1458

### CODE REVIEW

**Comment by olifolkerd** [comment]
Thanks for the submission, i will be reviewing pull requests on the weekend and will look at merging it in then :)

**Comment by olifolkerd** [comment]
All looks good,

i will merge this in for todays patch release.

Thanks for the contribution.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dahfazz 

Just a quick note, i didn't notice it when i approved your pull request, but you should not under any circumstance alter the git ignore file in a pull request to an NPM hosted repo.

All the generated code is committed because it is used by libraries like NPM that need the CSS and JS files.

When i merged in the pull request and released it on NPM it removed the dist folder from the distribution and broke the package for all users :(

As i say i should  have spotted it in your pull request, but just something for you to bare in mind for any future requests you make to other projects.

Cheers

Oli :)

**Comment by dahfazz** [comment]
Sincerely sorry.
I'll keep in mind for further contributions

**Comment by olifolkerd** [comment]
No need to apologies, 

As i say i should have caught it, just thought it would be a useful bit of info to pass on.

Thanks for your contribution, and you are most welcome to contribute again :) 

Cheers

Oli :)

**Pull request merged**
