### PR TITLE
enable header menu for column groups

### PR DESCRIPTION
**Pull request by thenesk**
A small addition to _buildGroupHeader so that it calls menu.initializeColumnHeader (just like what _buildColumnHeader does for non-group column headers).  This lets column group headers have context menus just regular column headers.

### CODE REVIEW

**Comment by thenesk** [comment]
This PR is in response to issue: https://github.com/olifolkerd/tabulator/issues/2803

I should have studied the existing PRs more carefully as there is already a PR for adding context menus for column groups: https://github.com/olifolkerd/tabulator/pull/2757

I am new to this code base and not sure what implementation is more appropriate.  For better or worse, this PR does not introduce new property names, it treats column group headers the same as column headers by checking for `headerMenu` and `headerContextMenu`.  That said, I see the existing PR is already slated for inclusion so I will not be offended if this PR is rejected.  :)

**Comment by olifolkerd** [comment]
Hey @thenesk 

Unless i am mistaken your PR is trying to do something very different to #2757, that PR is to add context menus to row groups, where as you are trying to add it to column groups

Cheers

Oli :)

**Comment by thenesk** [comment]
well in that case maybe my efforts are not wasted.  :)  Yes, I am interested in adding menus to column groups.

**Comment by olifolkerd** [comment]
Hey @thenesk 

Have you checked that this works correctly in a nested group scenario where each subgroup and column has their own context menu and that the correct menu is shown for each header.

Cheers

Oli :)

**Comment by thenesk** [comment]
I have not tried nested groups before, but I will try that

**Comment by thenesk** [comment]
@olifolkerd, you were right to suggest testing nested column groups each with their own menus.  With my original fix, the top level column group context menu  overshadowed the child columns.  I made a tweak to `Menu.initializeColumnHeader` so that the contextmenu event listener is attached to only the `contentElement` in the case that there are child columns.  The code is ready for your review.  Thanks!

**Comment by olifolkerd** [comment]
Hey @thenesk 

Thanks for looking into that.

One small tweak i would make, rather than checking to see if the group has children 'column.columns.length > 0', there is a boolean set on a column when it is initialised to determine if it is a group or not `column.isGroup`, That is what is used by most other parts of the system, so for consistence i would appreciate if you could take that apparoach.

Cheers

Oli :)

**Comment by thenesk** [comment]
Ok, change made.  :)

**Comment by olifolkerd** [comment]
Hey @thenesk 

Looking into your code a bit further i think the approach you have taken for the nesting of group header context menus may cause unexpected behaviour in certain scenarios.

Yes it certainly does allow for menus to exist at multiple levels on the header. but what if a person only wanted to define a header on the group and it be triggered with a context click anywhere in that header? with the current approach that wouldn't work.

Your initial approach failed because the event propagated, so while it may have initially loaded the correct menu in a nested group scenario it was immediately replaced with the menu of the parent.

We cant stop the event propagation because other events maybe bound to that listener higher up the chain, but inside the menu library we could look to block the immediate opening of a new menu if one has just opened

Cheers

Oli :)

**Comment by thenesk** [comment]
I am not quite sure what the code would look like, but I think I understand the behavior you are describing.  You would like the group level context menu to show when clicking a child if the child does not have a context menu of it own, right?  The current design does not have this behavior as default, but it can support it since the context menu can be applied to the children as desired.  So if someone wants all children to have the same context menu as their parent/group, then they can just set the property on each of the children to the desired menu.

If we make the group context menu apply automatically to all children, then that could save a bit of code for users that want that behavior by default.  But it could complicate things if a user wants the context menu to only apply to the group level and not have a context menu on the children.

For my case it does not matter too much which way you want this to work, I am just trying to think through the use cases.

**Comment by thenesk** [comment]
One possible implementation might be for a column to have a recursive function for getting the header context menu.  If there isn't a locally defined headerContextMenu, but there is a parent column, then call the parent column's getter function.  Is that the sort of thing you are looking for?

**Comment by olifolkerd** [comment]
Hey @thenesk 

I think it would have to work the other way round, otherwise we would have to search for a header menu anytime the header is clicked even if it isnt set. we probably want to sore the menu for the header in the headers module object, if there is one for a parent group it is set to that, otherwise it it set to the current headers menu.

I hope that makes sense.

Cheers

Oli :)

**Comment by thenesk** [comment]
I think I got it working the way you want using one of your earlier suggestions, blocking the creation of a menu if a menu is already open.  This seems to allow child menus to take precedence if defined.  Take a look and let me know.  Thanks,
Mark

**Comment by olifolkerd** [comment]
Hey @thenesk 

Nice approach there.  Happy to merge this in, It will be available in the 4.7 release later today.

Cheers

Oli :)

**Pull request merged**
