### PR TITLE
Fixes bug #2398

### PR DESCRIPTION
**Pull request by Darkseal**
https://github.com/olifolkerd/tabulator/issues/2398

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @Darkseal 

Thanks for your PR. Good catch there.

If you can remove your spacing on your if statements (before and after the parenthesis) i would be happy to accept the pull request. The coding style used in tabulator does not have spacing added around parenthesis in function definitions or logic statements.

Cheers

Oli :)

**Comment by Darkseal** [comment]
Done, let me know if that's ok now!

**Comment by olifolkerd** [comment]
Hey @Darkseal 

Thanks for making those tweaks, if you have a look at the diff for this you will see the following code replace:
```js
- data.forEach(function(row){
+ data.forEach(function (row) {
```

Which serves no purpose other than yo adjust the formatting, please remove that an we are goo to go!

Cheers

Oli :)

**Comment by Darkseal** [comment]
> - data.forEach(function(row){
> + data.forEach(function (row) {

Done!

**Comment by olifolkerd** [comment]
Sorry for the late reply,

Im happy to approve this, i will merge it in now and include it in the 4.5 release in a couple of weeks.

Cheers

Oli :)

**Pull request merged**
