### PR TITLE
Allow JSON downloader to use `titleDownload`

### LINKED ISSUE #3235: JSON export ignores 'titleDownload'
Take the following column:
```js
const columns = [ 
  {
    field: "a",
   title: "name",
   titleDownload: "Full Name"
  }

```

In the final json download we expect:

```json
{ "Full Name": "Bob Bobson" }
```

But we get:

```json
{ "a": "Bob Bobson" }
```

### PR DESCRIPTION
**Pull request by rathboma**
fixes #3235

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @rathboma 

As with the other PRs (great to see you contributing so much, Thanks :))

Could you resumbit this against the 5.0 branch ive made significant changes to the file structure and i wont be able to easily merge in changes on master.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

This is the intended behaviour of the download as the json is a data object it includes the field property of the data not its title.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Reopened as it can see that this is a useful work around for altering the property values

**Comment by rathboma** [comment]
See the new PR

**Pull request closed without merging**
