### PR TITLE
Adding ability to disable multiple column sort.

### PR DESCRIPTION
**Pull request by erez86**
Hi @olifolkerd,
We need an ability to only single sort a column and it doesn't exist,
please review our pull request for it.

Thanks a lot 👍

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hey @erez86 

Thanks for submitting your idea, I think it is a great addition but could i ask that you change the option name to ***columnHeaderSortMulti*** with a default value of true.

Then i would be happy to accept the pull request.

Cheers

Oli :)

**Comment by mikila85** [comment]
@olifolkerd we closed this by mistake is there any way to reopen or we need to resubmit?

**Comment by olifolkerd** [comment]
Hey @erez86 

Just to let you know, i am still very interested in including this in Tabulator, i will be looking at merging this in when i pull in the 4.1 branch in a couple of weeks or so.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
All merged in!


Thanks for the contribution :D

**Comment by olifolkerd** [comment]
All merged in!

Thanks for your contribution :D

**Pull request merged**
